# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/ci.yml"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  install-hictk:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, macos-14, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: "hictk"

    - name: conda info
      run: conda search -c conda-forge -c bioconda hictk --info || true

    - name: conda install
      if: matrix.platform != 'macos-14'
      run: conda install -c conda-forge -c bioconda hictk

    - name: conda install
      if: matrix.platform == 'macos-14'
      run: CONDA_SUBDIR=osx-64 conda install -c conda-forge -c bioconda hictk

